dist: xenial
sudo: required
language: python
python: 
    - '3.7'
before_install:
    # https://github.com/paulheider/Kivy-Travis-CI-Template/blob/master/.travis.yml
    # Required by Buildozer Android
    # https://buildozer.readthedocs.io/en/latest/installation.html#android-on-ubuntu-12-04-64bit
    - sudo apt-get update -q
    - sudo apt-get install build-essential ccache git lib32z1 lib32bz2-1.0 libncurses5:i386 libstdc++6:i386 python2.7 python2.7-dev openjdk-7-jdk unzip zlib1g-dev zlib1g:i386
    # Required by Kivy
    # https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2
    - sudo apt-get install python-pip build-essential git python-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
install:
    - pip install codecov
    - pip install --install-option="--no-cython-compile" "cython>0.27.2"
    - pip install pipenv
    - pipenv sync
addons:
    sonarcloud:
        organization: kristian-thy50409
script:
    - python -m pytest --cov-branch --cov-report term-missing:skip-covered --cov-report xml --cov=plateypus
after_success:
    - codecov
    - sonar-scanner
