dist: xenial
sudo: required
language: python
python: 
    - '3.7'
git:
    depth: false
cache: pip
services:
    - xvfb
before_install:
    - sudo add-apt-repository -y ppa:kivy-team/kivy
    - sudo apt-get update
    - sudo apt-get install -y python3-kivy build-essential python3-dev libav-tools libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
install:
    - pip install codecov
    - pip install --install-option="--no-cython-compile" "cython>0.27.2"
    - pip install pipenv
    - pipenv sync
    - garden install --app iconfonts
addons:
    sonarcloud:
        organization: kristian-thy50409
script:
    - python -m pytest --cov-branch --cov-report term-missing:skip-covered --cov-report xml --cov=plateypus
after_success:
    - codecov
    - sonar-scanner
